GET http://127.0.0.1:8000/orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU0MTI4NDQ1LCJpYXQiOjE3NTQxMjgxNDUsImp0aSI6ImQxNTAxZTQ3OTZkOTQ1ODdiY2IxMWUyMGEwMjkzMTViIiwidXNlcl9pZCI6IjEifQ.QRzrobqhGxAmbubSEATnVseDnCdvkTx7sOl0bNJQZMI

###

POST http://127.0.0.1:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUzODk4MTkzLCJpYXQiOjE3NTM4OTc4OTMsImp0aSI6ImU0NGRiMjdiYzg1YTRkOGZiMWUzYmQ4Y2JmYzg0NWE0IiwidXNlcl9pZCI6IjEifQ.18EdUs_fuHoQ09VHmqc_Fgf-gRc7S5TMZaEIBzkQJV4

{
    "name": "Television",
	"price": 300.00,
	"stock": 14,
	"description": "An amazing new TV"   
}

###
POST http://127.0.0.1:8000/api/token/ HTTP/1.1
Content-Type: application/json 

{
	"username":"admin",
	"password":"test"
}

### 
POST http://127.0.0.1:8000/api/token/ HTTP/1.1
Content-Type: application/json 

{
	"username":"Yousef",
	"password":"123"
}

###
POST http://127.0.0.1:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
	"refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MzI2NjI5NCwiaWF0IjoxNzUzMTc5ODk0LCJqdGkiOiJiN2Y5MGNmMWQyZmU0OTkyODFkYTdmMDE1MWM2ZjIzMSIsInVzZXJfaWQiOiIxIn0.KZj1KMRSWzMhF2H51K3GW8kw2MfVmHWzBaxZ2WzoY6E"
}

###
POST http://localhost:8000/orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU0MDYxOTI3LCJpYXQiOjE3NTQwNjE2MjcsImp0aSI6IjhhMWI1ZTMzMWM3YTQ1ZmZiZGU4YzQ5YTA3NTJjNTQ5IiwidXNlcl9pZCI6IjEifQ.3UHe8vmc6MfR7g-GIrEgT0dRoMHCzWUv4BMJNu7mFwc

{
	"status": "Pending",
	"items": [
		{
				"product": 2,
				"quantity": 2
		},
		{
				"product": 3,
				"quantity": 1
		}
	]	
}
###
PUT http://localhost:8000/orders/b817202b-2083-4467-b2f5-3169e1f6bfff/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU0MTI4NDQ1LCJpYXQiOjE3NTQxMjgxNDUsImp0aSI6ImQxNTAxZTQ3OTZkOTQ1ODdiY2IxMWUyMGEwMjkzMTViIiwidXNlcl9pZCI6IjEifQ.QRzrobqhGxAmbubSEATnVseDnCdvkTx7sOl0bNJQZMI


{
	"status": "Pending",
	"items": [
		{
				"product": 1,
				"quantity": 5
		},
		{
				"product": 2,
				"quantity": 4
		}
	]	
}
###
DELETE http://localhost:8000/orders/b817202b-2083-4467-b2f5-3169e1f6bfff/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU0MTI4Nzg0LCJpYXQiOjE3NTQxMjg0ODQsImp0aSI6IjI3YTk2ZmM0ZDAyNDRhODY5ZjU5NjhkZTlkYjcxNDE2IiwidXNlcl9pZCI6IjEifQ.Rrhi9avvRHzEthENSpR9zwfetb_jkqGcoMLI-PAkt7Q